# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

# Fabric — check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod
version=0.1.0
maven_group=dev.holoplace
archives_base_name=holoplace

# Dependencies
fabric_api_version=0.155.2+26.1.2
